// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4hlbT0P_UeWHj0zV6HXnYAA_IEmlWp6Y',
    appId: '1:78499670368:web:0c9161f9bfd8ae6c649605',
    messagingSenderId: '78499670368',
    projectId: 'takeit-9b0cb',
    authDomain: 'takeit-9b0cb.firebaseapp.com',
    storageBucket: 'takeit-9b0cb.firebasestorage.app',
    measurementId: 'G-BLC1J5HS57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5V9z7mqmB62NEIQan6hIFA9qDjtx6_SE',
    appId: '1:78499670368:android:830d305f8f4ee515649605',
    messagingSenderId: '78499670368',
    projectId: 'takeit-9b0cb',
    storageBucket: 'takeit-9b0cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4NASxRjIg66G5vs3nkW7tVxxKX51tngk',
    appId: '1:78499670368:ios:d98e026df095b6a3649605',
    messagingSenderId: '78499670368',
    projectId: 'takeit-9b0cb',
    storageBucket: 'takeit-9b0cb.firebasestorage.app',
    iosClientId: '78499670368-qd2acdapnn50n7jntgbr7cjvku6556cs.apps.googleusercontent.com',
    iosBundleId: 'com.example.takeittt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4NASxRjIg66G5vs3nkW7tVxxKX51tngk',
    appId: '1:78499670368:ios:d98e026df095b6a3649605',
    messagingSenderId: '78499670368',
    projectId: 'takeit-9b0cb',
    storageBucket: 'takeit-9b0cb.firebasestorage.app',
    iosClientId: '78499670368-qd2acdapnn50n7jntgbr7cjvku6556cs.apps.googleusercontent.com',
    iosBundleId: 'com.example.takeittt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4hlbT0P_UeWHj0zV6HXnYAA_IEmlWp6Y',
    appId: '1:78499670368:web:20771b7f61fd8342649605',
    messagingSenderId: '78499670368',
    projectId: 'takeit-9b0cb',
    authDomain: 'takeit-9b0cb.firebaseapp.com',
    storageBucket: 'takeit-9b0cb.firebasestorage.app',
    measurementId: 'G-T6MLPEMXMP',
  );
}
